# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4cd80f3cc73bb063d870b0fca707dbe37409d577bf957c4af674986e9feee6c32ab630168fb7c0336e1b29750bc0322fe13df0e7861f0e47681187311ae79929

test:
  secret_key_base: 4455805bb65f74a3261338cc96d9227d287b835f8ca121eb6fe7408664d0831684f124db941bc06182eb0884424fe20a0d5d5416b9a7b830366218a8de4ea1d0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
